### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by Manhbk97** [ros2-gbp/ros2-gbp-github-org#312] opened 2023-08-13 06:50 UTC
* Name of the new release team: 
* Release repositories to add:
  
  * [FIRST_REPOSITORY](https://github.com/Manhbk97/mapless_navigation_ros2)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [x ] There is an existing release repository which should be imported: [(https://github.com/Manhbk97/mapless_navigation_ros2-release
* Team members
  * [@Manhbk97](LINK TO SOURCE PACKAGE.XML MAINTAINER/AUTHOR TAG)

**Comment by nuclearsandwich** [comment] 2023-08-19 07:12
Incomplete duplicate of https://github.com/ros2-gbp/ros2-gbp-github-org/issues/311

**Closed as completed by nuclearsandwich** 2023-08-19 07:12 UTC
