### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by Myzhar** [ros2-gbp/ros2-gbp-github-org#653] opened 2024-11-21 10:27 UTC
* Name of the release team: Stereolabs

* Release repositories to add:
  
  * [zed-ros2-interfaces](https://github.com/stereolabs/zed-ros2-interfaces.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L11438-L11443)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment] 2024-11-21 18:09
Duplicate of #652.

**Closed as completed by nuclearsandwich** 2024-11-21 18:09 UTC
