### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by deyouslamtec** [ros2-gbp/ros2-gbp-github-org#236] opened 2023-04-06 02:11 UTC
* Name of the new release team: rplidar
* Release repositories to add:
  * [sllidar](https://github.com/Slamtec/sllidar_ros2)
    * https://github.com/Slamtec/sllidar_ros2

* Team members
  * [@slamtec](https://github.com/Slamtec/sllidar_ros2/blob/main/package.xml#L9)

**Comment by nuclearsandwich** [comment] 2023-04-11 17:15
Closing as a duplicate of #238 which has a pending response.

**Comment by nuclearsandwich** [comment] 2023-04-11 17:15
> Closing as a duplicate of #238 which has a pending response.

This was my mistake. I got issues and PRs confused.

**Comment by nuclearsandwich** [comment] 2023-05-06 00:12
Closing pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/238#issuecomment-1534014798

**Closed as completed by nuclearsandwich** 2023-05-06 00:12 UTC
