### ISSUE TITLE
Add new release repositories for ROS 2 FlexBE release

### ISSUE THREAD

**Issue by dcconner** [ros2-gbp/ros2-gbp-github-org#290] opened 2023-06-29 15:33 UTC
* Name of the release team: 
flexbe 
 Pending https://github.com/ros2-gbp/ros2-gbp-github-org/issues/289

* Release repositories to add:

Proposed for naming review in https://github.com/ros/rosdistro/pull/37823
  * https://github.com/ros2-gbp/flexbe_app-release.git
  * https://github.com/ros2-gbp/flexbe_behavior_engine-release.git
  

I planned to create new release repos, but the existing ROS 1 release repos are at :

  * [flexbe_app](https://github.com/flexbe/flexbe_app.git)
    * [ros/rosdistro source entry pending PR](https://github.com/ros/rosdistro/pull/37823
)
    * [ ] There is an existing release repository which should be imported: https://github.com/FlexBE/flexbe_app-release
  * [flexbe_behavior_engine](https://github.com/flexbe/flexbe_behavior_engine.git)
    * [ros/rosdistro source entry pending PR](https://github.com/ros/rosdistro/pull/37823
)
    * [ ] There is an existing release repository which should be imported: https://github.com/FlexBE/flexbe_behavior_engine-release

**Comment by nuclearsandwich** [comment] 2023-07-01 00:41
Duplicate of #289 since both request the new team and release repositories.

**Closed as completed by nuclearsandwich** 2023-07-01 00:41 UTC
